

SELECT 
D_DATA.NR_ANO,
SUM(F.QT_DE_PEDIDOS)  QT_DE_PEDIDOS,
SUM(F.VL_PEDIDO) VL_PEDIDO
FROM 
F_PEDIDO F,
D_DATA   
WHERE 
F.SK_DT_PEDIDO = D_DATA.SK_DATA
GROUP BY 
D_DATA.NR_ANO
ORDER BY NR_ANO

--2021	88560	23074507.67

SELECT 
D_DATA.NR_ANO,
SUM(F.VL_PEDIDO) VL_PEDIDO,
SUM(F.QT_DE_PEDIDOS)  QT_DE_PEDIDOS
FROM 
F_PEDIDO_RSM F,
D_DATA   
WHERE 
F.SK_MES_PEDIDO = D_DATA.SK_DATA
GROUP BY 
D_DATA.NR_ANO
ORDER BY NR_ANO





SELECT
D_LOJA.NM_LOJA,
D_LOJA.NM_CIDADE,
D_LOJA.SG_ESTADO,
SUM(F.VL_PEDIDO) VL_PEDIDO
FROM 
F_PEDIDO F,
D_DATA,
D_LOJA
WHERE 
     F.SK_DT_PEDIDO = D_DATA.SK_DATA
AND  F.SK_LOJA      = D_LOJA.SK_LOJA
AND  D_DATA.NR_ANO  = 2019
GROUP BY 
D_LOJA.NM_LOJA,
D_LOJA.NM_CIDADE,
D_LOJA.SG_ESTADO
ORDER BY VL_PEDIDO DESC
ORDER BY NR_ANO



SELECT
D_PRODUTO.DS_CATEGORIA_PROD,
D_PRODUTO.DS_SUB_CATEGORIA_PROD,
SUM(F.VL_PEDIDO) VL_PEDIDO
FROM 
F_PEDIDO F,
D_DATA,
D_PRODUTO 
WHERE 
     F.SK_DT_PEDIDO = D_DATA.SK_DATA
AND  F.SK_PRODUTO     = D_PRODUTO.SK_PRODUTO
AND  D_DATA.NR_ANO  = 2019
GROUP BY 
D_PRODUTO.DS_CATEGORIA_PROD,
D_PRODUTO.DS_SUB_CATEGORIA_PROD
ORDER BY VL_PEDIDO DESC