-- Gerado por Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   em:        2024-08-30 17:40:23 BRT
--   site:      SQL Server 2012
--   tipo:      SQL Server 2012

DROP TABLE IF EXISTS STG_DB_BAIRRO
GO

CREATE TABLE STG_DB_BAIRRO 
    (
     CD_BAIRRO INTEGER NOT NULL , 
     CD_CIDADE SMALLINT NOT NULL , 
     NM_BAIRRO VARCHAR (45) , 
     NM_ZONA_BAIRRO VARCHAR (20) 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Esta coluna irá receber o codigo do bairro e seu conteúdo é obrigatório.' , 'USER' , 'dbo' , 'TABLE' , 'STG_DB_BAIRRO' , 'COLUMN' , 'CD_BAIRRO' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Esta coluna irá receber a localização da zona onde se encontra o bairro. Alguns exemplos: Zona Norte, Zona Sul, Zona Leste, Zona Oeste, Centro.' , 'USER' , 'dbo' , 'TABLE' , 'STG_DB_BAIRRO' , 'COLUMN' , 'NM_ZONA_BAIRRO' 
GO

ALTER TABLE STG_DB_BAIRRO ADD CONSTRAINT PK_STG_DB_BAIRRO PRIMARY KEY CLUSTERED (CD_BAIRRO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_CARGO
GO

CREATE TABLE STG_DB_CARGO 
    (
     CD_CARGO SMALLINT NOT NULL , 
     CD_DEPTO SMALLINT NOT NULL , 
     DS_CARGO VARCHAR (50) NOT NULL , 
     ST_CARGO CHAR (1) NOT NULL 
    )
GO

ALTER TABLE STG_DB_CARGO ADD CONSTRAINT PK_STG_DB_CARGO PRIMARY KEY CLUSTERED (CD_CARGO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_CATEGORIA_PROD
GO


CREATE TABLE STG_DB_CATEGORIA_PROD 
    (
     CD_CATEGORIA_PROD SMALLINT NOT NULL , 
     DS_CATEGORIA_PROD VARCHAR (100) NOT NULL , 
     ST_CATEGORIA_PROD CHAR (1) NOT NULL 
    )
GO

ALTER TABLE STG_DB_CATEGORIA_PROD ADD CONSTRAINT PK_STG_DB_CATEGORIA_PRODUTO PRIMARY KEY CLUSTERED (CD_CATEGORIA_PROD)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_CIDADE
GO


CREATE TABLE STG_DB_CIDADE 
    (
     CD_CIDADE SMALLINT NOT NULL , 
     SG_ESTADO CHAR (2) NOT NULL , 
     NM_CIDADE VARCHAR (60) NOT NULL , 
     CD_IBGE NUMERIC (8) , 
     NR_DDD NUMERIC (3) 
    )
GO 



EXEC sp_addextendedproperty 'MS_Description' , 'Esta coluna irá receber o codigo da cidade e seu conteúdo é obrigatório.' , 'USER' , 'dbo' , 'TABLE' , 'STG_DB_CIDADE' , 'COLUMN' , 'CD_CIDADE' 
GO



EXEC sp_addextendedproperty 'MS_Description' , 'Esta coluna irá receber o código do IBGE que fornece informações para geração da NFe.' , 'USER' , 'dbo' , 'TABLE' , 'STG_DB_CIDADE' , 'COLUMN' , 'CD_IBGE' 
GO

ALTER TABLE STG_DB_CIDADE ADD CONSTRAINT PK_STG_DB_CIDADE PRIMARY KEY CLUSTERED (CD_CIDADE)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_CLI_FISICA
GO

CREATE TABLE STG_DB_CLI_FISICA 
    (
     NR_CLIENTE INTEGER NOT NULL , 
     DT_NASCIMENTO DATE NOT NULL , 
     FL_SEXO_BIOLOGICO CHAR (1) NOT NULL , 
     DS_GENERO VARCHAR (100) , 
     NR_CPF VARCHAR (14) NOT NULL 
    )
GO

ALTER TABLE STG_DB_CLI_FISICA ADD CONSTRAINT PK_STG_DB_CLI_FISICA PRIMARY KEY CLUSTERED (NR_CLIENTE)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_CLI_JURIDICA
GO

CREATE TABLE STG_DB_CLI_JURIDICA 
    (
     NR_CLIENTE INTEGER NOT NULL , 
     DT_FUNDACAO DATE , 
     NR_CNPJ VARCHAR (20) , 
     NR_INSCR_EST VARCHAR (15) 
    )
GO

ALTER TABLE STG_DB_CLI_JURIDICA ADD CONSTRAINT PK_STG_DB_CLI_JURIDICA PRIMARY KEY CLUSTERED (NR_CLIENTE)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_CLIENTE
GO

CREATE TABLE STG_DB_CLIENTE 
    (
     NR_CLIENTE INTEGER NOT NULL , 
     NM_CLIENTE VARCHAR (160) NOT NULL , 
     QT_ESTRELAS NUMERIC (1) , 
     VL_MEDIO_COMPRA NUMERIC (10,2) , 
     ST_CLIENTE CHAR (1) , 
     DS_EMAIL VARCHAR (100) , 
     NR_TELEFONE VARCHAR (20) 
    )
GO

ALTER TABLE STG_DB_CLIENTE ADD CONSTRAINT PK_STG_DB_CLIENTE PRIMARY KEY CLUSTERED (NR_CLIENTE)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_DEPTO
GO

CREATE TABLE STG_DB_DEPTO 
    (
     CD_DEPTO SMALLINT NOT NULL , 
     NM_DEPTO VARCHAR (100) NOT NULL , 
     NR_LOJA SMALLINT NOT NULL , 
     ST_DEPTO CHAR (1) NOT NULL 
    )
GO

ALTER TABLE STG_DB_DEPTO ADD CONSTRAINT PK_STG__DB_DEPTO PRIMARY KEY CLUSTERED (CD_DEPTO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


DROP TABLE IF EXISTS STG_DB_END_CLI
GO

CREATE TABLE STG_DB_END_CLI 
    (
     NR_CLIENTE INTEGER NOT NULL , 
     CD_LOGRADOURO_CLI INTEGER NOT NULL , 
     NR_END NUMERIC (8) NOT NULL , 
     DS_COMPLEMENTO_END VARCHAR (80) , 
     DT_INICIO DATE , 
     DT_TERMINO DATE , 
     ST_END CHAR (1) 
    )
GO 





ALTER TABLE STG_DB_END_CLI ADD CONSTRAINT PK_STG_DB_END_CLI PRIMARY KEY CLUSTERED (NR_CLIENTE, CD_LOGRADOURO_CLI)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


DROP TABLE IF EXISTS STG_DB_END_LOJA
GO


CREATE TABLE STG_DB_END_LOJA 
    (
     CD_LOJA_END INTEGER NOT NULL , 
     NR_LOJA SMALLINT NOT NULL , 
     CD_LOGRADOURO INTEGER NOT NULL , 
     NR_END NUMERIC (8) NOT NULL , 
     DS_COMPLEMENTO_END VARCHAR (80) , 
     DT_INICIO DATE NOT NULL , 
     DT_TERMINO DATE , 
     ST_END CHAR (1) NOT NULL 
    )
GO 







ALTER TABLE STG_DB_END_LOJA ADD CONSTRAINT STG_DB_END_FUNCv1_PK PRIMARY KEY CLUSTERED (CD_LOJA_END)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


DROP TABLE IF EXISTS STG_DB_ESTADO
GO

CREATE TABLE STG_DB_ESTADO 
    (
     SG_ESTADO CHAR (2) NOT NULL , 
     NM_ESTADO VARCHAR (30) NOT NULL 
    )
GO 





ALTER TABLE STG_DB_ESTADO ADD CONSTRAINT PK_STG_DB_ESTADO PRIMARY KEY CLUSTERED (SG_ESTADO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


DROP TABLE IF EXISTS STG_DB_FORMA_PAGAMENTO
GO

CREATE TABLE STG_DB_FORMA_PAGAMENTO 
    (
     CD_FORMA_PAGTO SMALLINT NOT NULL , 
     DS_FORMA_PAGTO VARCHAR (30) NOT NULL , 
     ST_FORMA_PAGTO CHAR (1) NOT NULL 
    )
GO

ALTER TABLE STG_DB_FORMA_PAGAMENTO ADD CONSTRAINT PK_STG_DB_FORMA_PAGAMENTO PRIMARY KEY CLUSTERED (CD_FORMA_PAGTO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


DROP TABLE IF EXISTS STG_DB_FUNCIONARIO
GO

CREATE TABLE STG_DB_FUNCIONARIO 
    (
     CD_FUNCIONARIO SMALLINT NOT NULL , 
     CD_GERENTE SMALLINT , 
     CD_CARGO SMALLINT NOT NULL , 
     NM_FUNCIONARIO VARCHAR (160) , 
     DT_NASCIMENTO DATE NOT NULL , 
     FL_SEXO_BIOLOGICO CHAR (1) , 
     DS_GENERO VARCHAR (100) , 
     VL_SALARIO_FAMILIA NUMERIC (10,2) , 
     VL_SALARIO_BRUTO NUMERIC (10,2) , 
     QT_TOT_DEPENDENTE NUMERIC (5) , 
     ST_FUNC CHAR (1) , 
     NR_PERC_COMISSAO NUMERIC (5,2) , 
     DT_CADASTRAMENTO DATE , 
     DT_DESLIGAMENTO DATE , 
     FT_FUNCIONARIO IMAGE 
    )
GO

ALTER TABLE STG_DB_FUNCIONARIO ADD CONSTRAINT PK_STG_DB_FUNCIONARIO PRIMARY KEY CLUSTERED (CD_FUNCIONARIO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


DROP TABLE IF EXISTS STG_DB_ITEM_PEDIDO
GO

CREATE TABLE STG_DB_ITEM_PEDIDO 
    (
     NR_LOJA SMALLINT NOT NULL , 
     NR_PEDIDO INTEGER NOT NULL , 
     NR_ITEM SMALLINT NOT NULL , 
     CD_PRODUTO_LOJA INTEGER NOT NULL , 
     QT_PEDIDO NUMERIC (8,2) , 
     VL_UNITARIO NUMERIC (8,2) , 
     VL_LUCRO_LIQUIDO NUMERIC (8,2) , 
     ST_ITEM_PEDIDO CHAR (1) 
    )
GO

ALTER TABLE STG_DB_ITEM_PEDIDO ADD CONSTRAINT PK_STG_DB_ITEM_PEDIDO PRIMARY KEY CLUSTERED (NR_PEDIDO, NR_LOJA, NR_ITEM)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


DROP TABLE IF EXISTS STG_DB_LOGRADOURO
GO


CREATE TABLE STG_DB_LOGRADOURO 
    (
     CD_LOGRADOURO INTEGER NOT NULL , 
     CD_BAIRRO INTEGER NOT NULL , 
     NM_LOGRADOURO VARCHAR (160) NOT NULL , 
     NR_CEP NUMERIC (8) 
    )
GO 




ALTER TABLE STG_DB_LOGRADOURO ADD CONSTRAINT PK_STG_DB_LOGRADOURO PRIMARY KEY CLUSTERED (CD_LOGRADOURO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO


DROP TABLE IF EXISTS STG_DB_LOJA
GO


CREATE TABLE STG_DB_LOJA 
    (
     NR_LOJA SMALLINT NOT NULL , 
     NM_LOJA VARCHAR (100) NOT NULL , 
     DT_INAUGURACAO DATE 
    )
GO

ALTER TABLE STG_DB_LOJA ADD CONSTRAINT PK_STG_DB_LOJA PRIMARY KEY CLUSTERED (NR_LOJA)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_PEDIDO
GO

CREATE TABLE STG_DB_PEDIDO 
    (
     NR_LOJA SMALLINT NOT NULL , 
     NR_PEDIDO INTEGER NOT NULL , 
     CD_FORMA_PAGTO SMALLINT NOT NULL , 
     NR_CLIENTE INTEGER NOT NULL , 
     CD_LOGRADOURO_CLI INTEGER NOT NULL , 
     CD_FUNC_ATD SMALLINT NOT NULL , 
     CD_FUNC_MOTOBOY SMALLINT , 
     DT_PEDIDO DATE NOT NULL , 
     DT_PREV_ENTREGA DATE , 
     VL_TOT_PEDIDO NUMERIC (10,2) , 
     ST_PEDIDO CHAR (1) NOT NULL 
    )
GO

ALTER TABLE STG_DB_PEDIDO ADD CONSTRAINT PK_STG_DB_PEDIDO PRIMARY KEY CLUSTERED (NR_LOJA, NR_PEDIDO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_PRODUTO
GO
CREATE TABLE STG_DB_PRODUTO 
    (
     CD_PRODUTO SMALLINT NOT NULL , 
     CD_SUB_CATEGORIA_PROD SMALLINT NOT NULL , 
     DS_PRODUTO VARCHAR (80) , 
     VL_UNITARIO NUMERIC (8,2) , 
     TP_EMBALAGEM VARCHAR (15) , 
     ST_PRODUTO CHAR (1) , 
     VL_PERC_LUCRO NUMERIC (8,2) , 
     DS_COMPLETA VARCHAR (4000) 
    )
GO

ALTER TABLE STG_DB_PRODUTO ADD CONSTRAINT PK_STG_DB_PRODUTO PRIMARY KEY CLUSTERED (CD_PRODUTO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_PRODUTO_LOJA
GO

CREATE TABLE STG_DB_PRODUTO_LOJA 
    (
     CD_PRODUTO_LOJA INTEGER NOT NULL , 
     NR_LOJA SMALLINT NOT NULL , 
     CD_PRODUTO SMALLINT NOT NULL , 
     DT_CADASTRO DATE NOT NULL , 
     ST_ATUAL CHAR (1) NOT NULL 
    )
GO

ALTER TABLE STG_DB_PRODUTO_LOJA ADD CONSTRAINT PK_STG_DB_PRODUTO_LOJA PRIMARY KEY CLUSTERED (CD_PRODUTO_LOJA)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_DB_SUB_CATEGORIA_PROD
GO

CREATE TABLE STG_DB_SUB_CATEGORIA_PROD 
    (
     CD_SUB_CATEGORIA_PROD SMALLINT NOT NULL , 
     CD_CATEGORIA_PROD SMALLINT NOT NULL , 
     DS_SUB_CATEGORIA_PROD VARCHAR (100) NOT NULL , 
     ST_SUB_CATEGORIA_PROD CHAR (1) NOT NULL 
    )
GO

ALTER TABLE STG_DB_SUB_CATEGORIA_PROD ADD CONSTRAINT STG_PK_DB_CATEGORIA PRIMARY KEY CLUSTERED (CD_SUB_CATEGORIA_PROD)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_F_PEDIDOS
GO

CREATE TABLE STG_F_PEDIDOS 
    (
     NR_LOJA SMALLINT NOT NULL , 
     NR_PEDIDO INTEGER NOT NULL , 
     NR_ITEM INTEGER NOT NULL , 
     CD_PRODUTO SMALLINT NOT NULL , 
     NR_CLIENTE INTEGER NOT NULL , 
	 CD_LOGRADOURO_CLI INTEGER NULL, 
     DT_PEDIDO DATE  NULL , 
     DT_PREV_ENTREGA DATE  NULL , 
     CD_FUNC_ATD INTEGER  NULL , 
     CD_FUNC_MOTOBOY INTEGER  NULL , 
     ST_PEDIDO CHAR (1) , 
     CD_FORMA_PAGTO SMALLINT  NULL , 
     CD_TIPO_PEDIDO CHAR (1) , 
     QT_PEDIDO NUMERIC (8,2)  NULL , 
     VL_UNITARIO NUMERIC (8,2)  NULL , 
     VL_PEDIDO NUMERIC (8,2)  NULL , 
     VL_LUCRO_LIQUIDO NUMERIC (8,2) , 
     DT_CRI_RGT DATETIME DEFAULT GETDATE() 
    )
GO

ALTER TABLE STG_F_PEDIDOS ADD CONSTRAINT STG_F_PEDIDOS_PK PRIMARY KEY CLUSTERED (NR_LOJA, NR_PEDIDO, NR_ITEM)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

DROP TABLE IF EXISTS STG_LOG_ETL
GO

CREATE TABLE STG_LOG_ETL 
    (
     ID_LOG_CARGA INTEGER NOT NULL IDENTITY NOT FOR REPLICATION , 
     NM_PACOTE VARCHAR (100) , 
     NM_CARGA VARCHAR (100) , 
     DT_INICIO DATETIME DEFAULT GETDATE() , 
     DT_FIM DATETIME , 
     QD_REGISTROS_ANTERIOR INTEGER , 
     QD_REGISTROS_FIM INTEGER , 
     ST_CARGA VARCHAR (20) 
    )
GO



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            22
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0