--STG_DB_BAIRRO

---LOG INÍCIO STG_DB_BAIRRO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_BAIRRO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_BAIRRO),
 NULL,
 'EM ANDAMENTO')

 ---LOG SUCESSO STG_DB_BAIRRO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_BAIRRO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_BAIRRO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_BAIRRO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_BAIRRO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_BAIRRO'
       AND NM_PACOTE = 'DATALAB_ETL_001')




--STG_DB_CARGO--
--LOG INÍCIO STG_DB_CARGO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_CARGO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_CARGO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_CARGO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CARGO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CARGO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_CARGO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CARGO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CARGO'
       AND NM_PACOTE = 'DATALAB_ETL_001')



--STG_DB_CATEGORIA_PROD--

--LOG INÍCIO STG_DB_CATEGORIA_PROD
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_CATEGORIA_PROD',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_CATEGORIA_PROD),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_CATEGORIA_PROD
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CATEGORIA_PROD),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CATEGORIA_PROD'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_CATEGORIA_PROD
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CATEGORIA_PROD),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CATEGORIA_PROD'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--STG_DB_CIDADE--

--LOG INÍCIO STG_DB_CIDADE
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_CIDADE',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_CIDADE),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_CIDADE
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CIDADE),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CIDADE'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_CIDADE
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CIDADE),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CIDADE'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--STG_DB_CLI_FISICA--

--LOG INÍCIO STG_DB_CLI_FISICA
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_CLI_FISICA',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_CLI_FISICA),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_CLI_FISICA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CLI_FISICA),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CLI_FISICA'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_CLI_FISICA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CLI_FISICA),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CLI_FISICA'
       AND NM_PACOTE = 'DATALAB_ETL_001')


--STG_DB_CLI_JURIDICA--

--LOG INÍCIO STG_DB_CLI_JURIDICA
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_CLI_JURIDICA',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_CLI_JURIDICA),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_CLI_JURIDICA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CLI_JURIDICA),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CLI_JURIDICA'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_CLI_JURIDICA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CLI_JURIDICA),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CLI_JURIDICA'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_CLIENTE--

 
--LOG INÍCIO STG_DB_CLIENTE
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_CLIENTE',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_CLIENTE),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_CLIENTE
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CLIENTE),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CLIENTE'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_CLIENTE
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_CLIENTE),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_CLIENTE'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_DEPTO--

 
--LOG INÍCIO STG_DB_DEPTO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_DEPTO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_DEPTO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_DEPTO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_DEPTO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_DEPTO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_DEPTO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_DEPTO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_DEPTO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_END_CLI--

 
--LOG INÍCIO STG_DB_END_CLI
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_END_CLI',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_END_CLI),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_END_CLI
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_END_CLI),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_END_CLI'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_END_CLI
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_END_CLI),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_END_CLI'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_END_LOJA--

 
--LOG INÍCIO STG_DB_END_LOJA
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_END_LOJA',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_END_LOJA),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_END_LOJA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_END_LOJA),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_END_LOJA'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_END_LOJA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_END_LOJA),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_END_LOJA'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_ESTADO--

 
--LOG INÍCIO STG_DB_ESTADO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_ESTADO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_ESTADO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_ESTADO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_ESTADO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_ESTADO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_ESTADO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_ESTADO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_ESTADO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_FORMA_PAGAMENTO--

 
--LOG INÍCIO STG_DB_FORMA_PAGAMENTO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_FORMA_PAGAMENTO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_FORMA_PAGAMENTO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_FORMA_PAGAMENTO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_FORMA_PAGAMENTO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_FORMA_PAGAMENTO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_FORMA_PAGAMENTO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_FORMA_PAGAMENTO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_FORMA_PAGAMENTO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_FUNCIONARIO--

 
--LOG INÍCIO STG_DB_FUNCIONARIO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_FUNCIONARIO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_FUNCIONARIO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_FUNCIONARIO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_FUNCIONARIO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_FUNCIONARIO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_FUNCIONARIO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_FUNCIONARIO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_FUNCIONARIO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_ITEM_PEDIDO--

 
--LOG INÍCIO STG_DB_ITEM_PEDIDO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_ITEM_PEDIDO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_ITEM_PEDIDO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_ITEM_PEDIDO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_ITEM_PEDIDO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_ITEM_PEDIDO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_ITEM_PEDIDO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_ITEM_PEDIDO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_ITEM_PEDIDO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_LOGRADOURO--

 
--LOG INÍCIO STG_DB_LOGRADOURO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_LOGRADOURO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_LOGRADOURO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_LOGRADOURO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_LOGRADOURO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_LOGRADOURO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_LOGRADOURO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_LOGRADOURO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_LOGRADOURO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_LOJA--

 
--LOG INÍCIO STG_DB_LOJA
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_LOJA',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_LOJA),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_LOJA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_LOJA),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_LOJA'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_LOJA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_LOJA),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_LOJA'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_PEDIDO--

 
--LOG INÍCIO STG_DB_PEDIDO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_PEDIDO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_PEDIDO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_PEDIDO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_PEDIDO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_PEDIDO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_PEDIDO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_PEDIDO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_PEDIDO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_PRODUTO--

 
--LOG INÍCIO STG_DB_PRODUTO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_PRODUTO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_PRODUTO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_PRODUTO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_PRODUTO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_PRODUTO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_PRODUTO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_PRODUTO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_PRODUTO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_PRODUTO_LOJA--

 
--LOG INÍCIO STG_DB_PRODUTO_LOJA
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_PRODUTO_LOJA',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_PRODUTO_LOJA),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_PRODUTO_LOJA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_PRODUTO_LOJA),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_PRODUTO_LOJA'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_PRODUTO_LOJA
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_PRODUTO_LOJA),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_PRODUTO_LOJA'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_DB_SUB_CATEGORIA_PROD--

 
--LOG INÍCIO STG_DB_SUB_CATEGORIA_PROD
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_SUB_CATEGORIA_PROD',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_DB_SUB_CATEGORIA_PROD),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_DB_SUB_CATEGORIA_PROD
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_SUB_CATEGORIA_PROD),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_SUB_CATEGORIA_PROD'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_DB_SUB_CATEGORIA_PROD
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_DB_SUB_CATEGORIA_PROD),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_DB_SUB_CATEGORIA_PROD'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_F_PEDIDO--

 
--LOG INÍCIO STG_F_PEDIDO
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_F_PEDIDO',
 GETDATE(),
 NULL, 
 (SELECT COUNT(1) FROM STG_F_PEDIDO),
 NULL,
 'EM ANDAMENTO')

---LOG SUCESSO STG_F_PEDIDO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_F_PEDIDO),
  ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_F_PEDIDO'
       AND NM_PACOTE = 'DATALAB_ETL_001')

--LOG ERRO STG_F_PEDIDO
   UPDATE STG_LOG_ETL
 SET DT_FIM = GETDATE(),
     QD_REGISTROS_FIM = (SELECT COUNT (1) FROM STG_F_PEDIDO),
  ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
                      FROM STG_LOG_ETL (NOLOCK)
       WHERE 
       NM_CARGA = 'STG_F_PEDIDO'
       AND NM_PACOTE = 'DATALAB_ETL_001')
 

--STG_LOG_ETL--

 
--LOG INÍCIO STG_LOG_ETL
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_LOG_ETL',