TRUNCATE TABLE STG_LOG_ETL;

SELECT * FROM STG_LOG_ETL ORDER BY ID_LOG_CARGA;

INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
  'DATALAB_ETL_001',
  GETDATE(),
  NULL,
  NULL,
  NULL,
  'EM ANDAMENTO')

INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_ESTADO',
  GETDATE(),
  NULL,
  (SELECT COUNT(1) FROM STG_DB_ESTADO),
  NULL,
  'EM ANDAMENTO')

INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_001',
 'STG_DB_CIDADE',
  GETDATE(),
  NULL,
  (SELECT COUNT(1) FROM STG_DB_CIDADE),
  NULL,
  'EM ANDAMENTO')

UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
	QD_REGISTROS_FIM = (SELECT COUNT(1) FROM STG_DB_ESTADO),
	ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
					  FROM STG_LOG_ETL (NOLOCK)
					  WHERE
					  NM_CARGA = 'STG_DB_ESTADO'
					  AND NM_PACOTE = 'DATALAB_ETL_001')

UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
	QD_REGISTROS_FIM = (SELECT COUNT(1) FROM STG_DB_ESTADO),
	ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
					  FROM STG_LOG_ETL (NOLOCK)
					  WHERE
					  NM_CARGA = 'STG_DB_ESTADO'
					  AND NM_PACOTE = 'DATALAB_ETL_001')

UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
	QD_REGISTROS_FIM = (SELECT COUNT(1) FROM STG_DB_CIDADE),
	ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
					  FROM STG_LOG_ETL (NOLOCK)
					  WHERE
					  NM_CARGA = 'STG_DB_CIDADE'
					  AND NM_PACOTE = 'DATALAB_ETL_001')

UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
	QD_REGISTROS_FIM = (SELECT COUNT(1) FROM STG_DB_CIDADE),
	ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
					  FROM STG_LOG_ETL (NOLOCK)
					  WHERE
					  NM_CARGA = 'STG_DB_CIDADE'
					  AND NM_PACOTE = 'DATALAB_ETL_001')

WAITFOR DELAY '00:00:03';

GO

-- LOG ERRO
UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
	ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
					  FROM STG_LOG_ETL (NOLOCK)
					  WHERE
					  NM_CARGA      = 'DATALAB_ETL_001'
					  AND NM_PACOTE = 'DATALAB_ETL_001')
AND EXISTS 
(SELECT 1 FROM STG_LOG_ETL (NOLOCK) X
WHERE
X.NM_PACOTE = 'DATALAB_ETL_001'
AND X.ST_CARGA = 'ERRO'
AND X.ID_LOG_CARGA > STG_LOG_ETL.ID_LOG_CARGA);

GO

-- LOG SUCESSO
UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
	ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
					  FROM STG_LOG_ETL (NOLOCK)
					  WHERE
					  NM_CARGA      = 'DATALAB_ETL_001'
					  AND NM_PACOTE = 'DATALAB_ETL_001'
					  AND DT_FIM IS NULL);

SELECT * FROM STG_DB_PEDIDO;
SELECT * FROM STG_DB_PRODUTO;
SELECT * FROM STG_DB_CATEGORIA_PROD;
SELECT * FROM STG_DB_SUB_CATEGORIA_PROD;
SELECT * FROM STG_DB_FORMA_PAGAMENTO;
SELECT * FROM STG_F_PEDIDO;
