-- Algumas querry's estao mostrando como se tivessem com erro pois estao sendo executadas na STAGEAREA E NAO NO DWBURGER
--LOG INICIO PACOTE REALIZADO NA STGAREA
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_002',
  'DATALAB_ETL_002',
  GETDATE(),
  NULL,
  NULL,
  NULL,
  'EM ANDAMENTO')

--LOG FIM PACOTE
WAITFOR DELAY '00:00:03';

GO

UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
 ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
       FROM STG_LOG_ETL (NOLOCK)
       WHERE
       NM_CARGA      = 'DATALAB_ETL_002'
       AND NM_PACOTE = 'DATALAB_ETL_002')
AND EXISTS 
(SELECT 1 FROM STG_LOG_ETL (NOLOCK) X
WHERE
X.NM_PACOTE = 'DATALAB_ETL_002'
AND X.ST_CARGA = 'ERRO'
AND X.ID_LOG_CARGA > STG_LOG_ETL.ID_LOG_CARGA);

GO

UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
 ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
       FROM STG_LOG_ETL (NOLOCK)
       WHERE
       NM_CARGA      = 'DATALAB_ETL_002'
       AND NM_PACOTE = 'DATALAB_ETL_002'
       AND DT_FIM IS NULL);

--LOG INICIO CARGA D_DATA REALIZADO NA STGAREA
INSERT INTO STG_LOG_ETL
VALUES
('DATALAB_ETL_002',
 'D_DATA',
  GETDATE(),
  NULL,
  (SELECT COUNT(1) FROM DWBURGER..D_DATA),
  NULL,
  'EM ANDAMENTO');

--LOG SUCESSO CARGA D_DATA REALIZADO NA STGAREA
UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
 QD_REGISTROS_FIM = (SELECT COUNT(1) FROM DWBURGER..D_DATA),
 ST_CARGA = 'SUCESSO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
       FROM STG_LOG_ETL (NOLOCK)
       WHERE
       NM_CARGA = 'D_DATA'
       AND NM_PACOTE = 'DATALAB_ETL_002')

--LOG ERRO CARGA D_DATA REALIZADO NA STGAREA
UPDATE STG_LOG_ETL
SET DT_FIM = GETDATE(),
 QD_REGISTROS_FIM = (SELECT COUNT(1) FROM DWBURGER..D_DATA),
 ST_CARGA = 'ERRO'
WHERE ID_LOG_CARGA = (SELECT MAX(ID_LOG_CARGA)
       FROM STG_LOG_ETL (NOLOCK)
       WHERE
       NM_CARGA = 'D_DATA'
       AND NM_PACOTE = 'DATALAB_ETL_002');

--CORRIGE DT_INICIO EM D_FUNCIONARIO
UPDATE D_FUNCIONARIO
SET DT_INICIO = '2018-01-01'
FROM
(SELECT CD_FUNCIONARIO,
MIN(SK_FUNCIONARIO) AS SK_FUNCIONARIO
FROM D_FUNCIONARIO
GROUP BY CD_FUNCIONARIO) SQ
WHERE SQ.CD_FUNCIONARIO = D_FUNCIONARIO.CD_FUNCIONARIO
AND DT_INICIO <> '2018-01-01'

--CORRIGE DT_INICIO EM D_PRODUTO
UPDATE D_PRODUTO
SET DT_INICIO = '2018-01-01'
FROM
(SELECT CD_PRODUTO,
MIN(SK_PRODUTO) AS SK_PRODUTO
FROM D_PRODUTO
GROUP BY CD_PRODUTO) SQ
WHERE SQ.CD_PRODUTO = D_PRODUTO.CD_PRODUTO
AND DT_INICIO <> '2018-01-01'

SELECT * FROM D_DATA;
SELECT * FROM D_CLIENTE;
SELECT * FROM D_LOJA;
SELECT * FROM D_PRODUTO;
SELECT * FROM D_FUNCIONARIO;
SELECT * FROM D_STATUS_TIPO;
SELECT * FROM F_PEDIDO;
SELECT * FROM F_PEDIDO_RSM;
