--SCRIPT SQL PARA POPULAR F_PEDIDO
SELECT
    STG.NR_LOJA,
    STG.NR_PEDIDO,
    STG.NR_ITEM,
    ISNULL(CAST(FORMAT(DT_PEDIDO, 'yyyyMMdd') AS INT), -2) AS SK_DT_PEDIDO,
    ISNULL(CAST(FORMAT(DT_PREV_ENTREGA, 'yyyyMMdd') AS INT), -2) AS SK_DT_PREV_ENTREGA,
    ISNULL(D_PRODUTO.SK_PRODUTO, -3) AS SK_PRODUTO,
    ISNULL(D_LOJA.SK_LOJA, -3) AS SK_LOJA,
    ISNULL(D_CLIENTE.SK_CLIENTE, -3) AS SK_CLIENTE,
    ISNULL(MBOY.SK_FUNCIONARIO, -3) AS SK_FUNC_MOTOBOY,
    ISNULL(ATD.SK_FUNCIONARIO, -3) AS SK_FUNC_ATD,
    ISNULL(D_STATUS_TIPO.SK_STATUS_TIPO, -3) AS SK_STATUS_TIPO,
    STG.QT_PEDIDO,
    STG.VL_UNITARIO,
    STG.VL_PEDIDO,
    STG.VL_LUCRO_LIQUIDO,
	CASE WHEN NR_ITEM = 1 THEN 1 ELSE 0 END AS QT_DE_PEDIDOS
FROM 
    STG_F_PEDIDO STG
LEFT JOIN 
    DWBURGER..D_PRODUTO ON (
        STG.CD_PRODUTO = D_PRODUTO.CD_PRODUTO
        AND DT_PEDIDO >= D_PRODUTO.DT_INICIO 
        AND (DT_PEDIDO < D_PRODUTO.DT_FIM OR D_PRODUTO.DT_FIM IS NULL)
    )
LEFT JOIN 
    DWBURGER..D_LOJA ON (
        STG.NR_LOJA = D_LOJA.NR_LOJA 
        AND DT_PEDIDO >= D_LOJA.DT_INICIO
        AND (DT_PEDIDO < D_LOJA.DT_TERMINO OR D_LOJA.DT_TERMINO IS NULL)
    )
LEFT JOIN 
    DWBURGER..D_CLIENTE ON (
        STG.NR_CLIENTE = D_CLIENTE.NR_CLIENTE
        AND STG.CD_LOGRADOURO_CLI = D_CLIENTE.CD_LOGRADOURO_CLI
    )
LEFT JOIN 
    DWBURGER..D_FUNCIONARIO MBOY ON (
        STG.CD_FUNC_MOTOBOY = MBOY.CD_FUNCIONARIO
        AND DT_PEDIDO >= MBOY.DT_INICIO 
        AND (DT_PEDIDO < MBOY.DT_FIM OR MBOY.DT_FIM IS NULL)
    )
LEFT JOIN 
    DWBURGER..D_FUNCIONARIO ATD ON (
        STG.CD_FUNC_ATD = ATD.CD_FUNCIONARIO
        AND DT_PEDIDO >= ATD.DT_INICIO 
        AND (DT_PEDIDO < ATD.DT_FIM OR ATD.DT_FIM IS NULL)
    )
LEFT JOIN 
    DWBURGER..D_STATUS_TIPO ON (
        STG.CD_FORMA_PAGTO = D_STATUS_TIPO.CD_FORMA_PAGTO
        AND STG.ST_PEDIDO = D_STATUS_TIPO.ST_PEDIDO
        AND STG.CD_TIPO_PEDIDO = D_STATUS_TIPO.CD_TIPO_PEDIDO
    )

