

UPDATE D_PRODUTO
SET    DT_INICIO = '2018-01-01'
FROM
(SELECT CD_PRODUTO, 
 MIN(SK_PRODUTO) AS SK_PRODUTO
 FROM   D_PRODUTO
 GROUP BY CD_PRODUTO) SQ
 WHERE SQ.CD_PRODUTO = D_PRODUTO.CD_PRODUTO
 AND   DT_INICIO <> '2018-01-01'

 GO
 
 UPDATE D_FUNCIONARIO
SET     DT_INICIO = '2018-01-01'
FROM
(SELECT CD_FUNCIONARIO, 
 MIN(SK_FUNCIONARIO) AS SK_FUNCIONARIO
 FROM   D_FUNCIONARIO
 GROUP BY CD_FUNCIONARIO) SQ
 WHERE SQ.CD_FUNCIONARIO = D_FUNCIONARIO.CD_FUNCIONARIO
 AND   DT_INICIO <> '2018-01-01'