SELECT
FP.CD_FORMA_PAGTO,
FP.DS_FORMA_PAGTO,
FP.ST_FORMA_PAGTO,
CASE 
WHEN FP.ST_FORMA_PAGTO = 'A' THEN 'Ativo' 
else 'Inativo'
end as DS_ST_FORMA_PAGTO,
TP.CD_TIPO_PEDIDO,
TP.DS_TIPO_PEDIDO,
SP.ST_PEDIDO,
SP.DS_ST_PEDIDO
From 
stg_db_forma_pagamento FP,
(SELECT 
'D'        AS CD_TIPO_PEDIDO,
'Delivery' AS DS_TIPO_PEDIDO
UNION ALL
SELECT 
'L'        AS CD_TIPO_PEDIDO,
'Loja'     AS DS_TIPO_PEDIDO) AS TP,
(SELECT
'A'        AS ST_PEDIDO,
'Ativo'    AS DS_ST_PEDIDO
UNION ALL
SELECT
'I'          AS ST_PEDIDO,
'Inativo'    AS DS_ST_PEDIDO) SP
ORDER BY 
CD_TIPO_PEDIDO,
ST_PEDIDO