--SQL SCRIPT PARA POPULAR STG_F_PEDIDO COM VARIÁVEIS
/* 
O primeiro ponto de interrogação será mapeado para a variável TP_CARGA, enquanto o segundo será mapeado para a variável DT_REFERENCIA.
TP_CARGA = 'F' indica carga FULL: traz todos os registros, sem filtrar por data
Quando TP_CARGA <> 'F', fazemos uma carga INCREMENTAL (ou PARCIAL), filtrando os registros a partir de DT_REFERENCIA
*/

SELECT
    STG_DB_ITEM_PEDIDO.NR_LOJA,
    STG_DB_ITEM_PEDIDO.NR_PEDIDO,
    STG_DB_ITEM_PEDIDO.NR_ITEM,
    STG_DB_PEDIDO.DT_PEDIDO,
    STG_DB_PEDIDO.DT_PREV_ENTREGA,
    ISNULL(STG_DB_PRODUTO_LOJA.CD_PRODUTO, -2) AS CD_PRODUTO,
    ISNULL(STG_DB_PEDIDO.NR_CLIENTE, -2) AS NR_CLIENTE,
    ISNULL(STG_DB_PEDIDO.CD_LOGRADOURO_CLI, -2) AS CD_LOGRADOURO_CLI,
    ISNULL(STG_DB_PEDIDO.CD_FUNC_ATD, -2) AS CD_FUNC_ATD,
    ISNULL(STG_DB_PEDIDO.CD_FUNC_MOTOBOY, -1) AS CD_FUNC_MOTOBOY,
    STG_DB_PEDIDO.CD_FORMA_PAGTO,
    CASE 
        WHEN STG_DB_PEDIDO.CD_FUNC_MOTOBOY IS NULL THEN 'L' 
        ELSE 'D' 
    END AS CD_TIPO_PEDIDO,
    STG_DB_PEDIDO.ST_PEDIDO,
    STG_DB_ITEM_PEDIDO.QT_PEDIDO,
    STG_DB_ITEM_PEDIDO.VL_UNITARIO,
    STG_DB_ITEM_PEDIDO.VL_LUCRO_LIQUIDO,
    STG_DB_ITEM_PEDIDO.VL_UNITARIO * STG_DB_ITEM_PEDIDO.QT_PEDIDO AS VL_PEDIDO
FROM 
    STG_DB_ITEM_PEDIDO 
JOIN 
    STG_DB_PRODUTO_LOJA ON STG_DB_ITEM_PEDIDO.CD_PRODUTO_LOJA = STG_DB_PRODUTO_LOJA.CD_PRODUTO_LOJA
JOIN 
    STG_DB_PEDIDO ON STG_DB_ITEM_PEDIDO.NR_LOJA = STG_DB_PEDIDO.NR_LOJA 
                 AND STG_DB_ITEM_PEDIDO.NR_PEDIDO = STG_DB_PEDIDO.NR_PEDIDO
WHERE
    (? = 'F' OR STG_DB_PEDIDO.DT_PEDIDO >= ?)
ORDER BY 
    NR_LOJA, NR_PEDIDO, NR_ITEM;
