SELECT 
D.NR_ANO_MES *100 + 1 SK_MES_PEDIDO,
F.SK_CLIENTE,
F.SK_LOJA,
F.QT_DE_PEDIDOS,
F.QT_PEDIDO,
F.VL_PEDIDO,
F.VL_LUCRO_LIQUIDO
FROM
F_PEDIDO F,
D_DATA   D
WHERE D.SK_DATA = F.SK_DT_PEDIDO
AND
(? = 'F' OR D.DT_REFERENCIA >= ?)
