SELECT
       PRD.CD_PRODUTO
      ,PRD.DS_PRODUTO
      ,PRD.VL_UNITARIO
      ,PRD.TP_EMBALAGEM
      ,PRD.ST_PRODUTO
	  ,CASE 
	  WHEN PRD.ST_PRODUTO = 'I' THEN 'Inativo' 
	  ELSE 'Ativo' END AS DS_ST_PRODUTO
      ,PRD.VL_PERC_LUCRO
      ,PRD.DS_COMPLETA
	  ,SUB.CD_SUB_CATEGORIA_PROD
      ,SUB.DS_SUB_CATEGORIA_PROD
      ,SUB.ST_SUB_CATEGORIA_PROD
	  ,CASE 
	  WHEN SUB.ST_SUB_CATEGORIA_PROD = 'I' THEN 'Inativo' 
	  ELSE 'Ativo' END AS DS_ST_SUB_CATEGORIA_PROD
	  ,CAT.CD_CATEGORIA_PROD
      ,CAT.DS_CATEGORIA_PROD
      ,CAT.ST_CATEGORIA_PROD
	  ,CASE 
	  WHEN CAT.ST_CATEGORIA_PROD = 'I' THEN 'Inativo' 
	  ELSE 'Ativo' END AS DS_ST_CATEGORIA
FROM
STG_DB_PRODUTO            PRD,
STG_DB_SUB_CATEGORIA_PROD SUB,
STG_DB_CATEGORIA_PROD     CAT
WHERE
    PRD.CD_SUB_CATEGORIA_PROD = SUB.CD_SUB_CATEGORIA_PROD
AND CAT.CD_CATEGORIA_PROD     = SUB.CD_CATEGORIA_PROD
