--SCRIPT SQL – SELEÇÃO DE DADOS PARA D_FUNCIONARIO
SELECT 
    STG_DB_FUNCIONARIO.cd_funcionario AS CD_FUNCIONARIO,
    STG_DB_FUNCIONARIO.nm_funcionario AS NM_FUNCIONARIO,
    CAST(STG_DB_FUNCIONARIO.dt_nascimento AS DATE) AS DT_NASCIMENTO,
    CAST(dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) AS TINYINT) AS NR_IDADE,

    CASE
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) BETWEEN 0 AND 10 THEN '00 a 10 anos'
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) BETWEEN 11 AND 20 THEN '11 a 20 anos' 
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) BETWEEN 21 AND 30 THEN '21 a 30 anos' 
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) BETWEEN 31 AND 40 THEN '31 a 40 anos' 
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) BETWEEN 41 AND 50 THEN '41 a 50 anos' 
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) BETWEEN 51 AND 60 THEN '51 a 60 anos' 
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) BETWEEN 61 AND 70 THEN '61 a 70 anos'
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_NASCIMENTO, GETDATE()) > 70 THEN 'Acima de 70 anos'
        ELSE 'VERIFICAR'
    END AS DS_FAIXA_ETARIA,

    STG_DB_FUNCIONARIO.FL_SEXO_BIOLOGICO,

    CAST(
        CASE 
            WHEN STG_DB_FUNCIONARIO.FL_SEXO_BIOLOGICO = 'F' THEN 'Feminino'
            WHEN STG_DB_FUNCIONARIO.FL_SEXO_BIOLOGICO = 'M' THEN 'Masculino'
            ELSE 'N/D' 
        END AS VARCHAR(9)
    ) AS DS_GENERO,

    STG_DB_FUNCIONARIO.VL_SALARIO_FAMILIA,
    STG_DB_FUNCIONARIO.VL_SALARIO_BRUTO,
    CAST(STG_DB_FUNCIONARIO.QT_TOT_DEPENDENTE AS TINYINT) AS QT_TOT_DEPENDENTE,
    STG_DB_FUNCIONARIO.NR_PERC_COMISSAO,
    STG_DB_FUNCIONARIO.ST_FUNC,

    CASE 
        WHEN STG_DB_FUNCIONARIO.ST_FUNC = 'A' THEN 'Ativo'
        WHEN STG_DB_FUNCIONARIO.ST_FUNC = 'I' THEN 'Inativo'
        ELSE 'N/D' 
    END AS DS_ST_FUNC,

    STG_DB_DEPTO.CD_DEPTO  ,
    STG_DB_DEPTO.NM_DEPTO,
    STG_DB_CARGO.CD_CARGO,
    STG_DB_CARGO.DS_CARGO,

    CASE
        WHEN STG_DB_FUNCIONARIO.VL_SALARIO_BRUTO <= 5000                   THEN '00 a 5.000'
        WHEN STG_DB_FUNCIONARIO.VL_SALARIO_BRUTO BETWEEN 5000.01 AND 10000 THEN '5.000 a 10.000'
        WHEN STG_DB_FUNCIONARIO.VL_SALARIO_BRUTO > 10000                   THEN 'Acima de 10.000'
        ELSE 'ERRO'
    END AS DS_FAIXA_SALARIAL,

    STG_DB_FUNCIONARIO.DT_CADASTRAMENTO,
    STG_DB_FUNCIONARIO.DT_DESLIGAMENTO,

    CASE 
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_CADASTRAMENTO, GETDATE()) BETWEEN 0 AND 5  THEN '00 a 05 anos'
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_CADASTRAMENTO, GETDATE()) BETWEEN 6 AND 10 THEN '06 a 10 anos'
        WHEN dbo.fn_GetAge(STG_DB_FUNCIONARIO.DT_CADASTRAMENTO, GETDATE()) > 10             THEN '11 anos ou mais'
    END AS DS_TEMPO_CASA,

    STG_DB_LOJA.NR_LOJA,
    STG_DB_LOJA.NM_LOJA,

    CAST(
        CASE 
            WHEN DS_CARGO IN ('Gestor(a)', 'Gerente') THEN -1
            ELSE GERENTE.CD_FUNCIONARIO 
        END AS SMALLINT
    ) AS CD_GERENTE,

    CASE 
        WHEN DS_CARGO IN ('Gestor(a)', 'Gerente') THEN 'Não se aplica'
        ELSE GERENTE.NM_FUNCIONARIO 
    END AS NM_GERENTE,

    CAST(
        CASE 
            WHEN DS_CARGO = 'Gestor(a)' THEN -1
            WHEN DS_CARGO = 'Gerente' THEN GERENTE.CD_FUNCIONARIO
            ELSE GESTOR.CD_FUNCIONARIO 
        END AS SMALLINT
    ) AS CD_GESTOR,

    CASE 
        WHEN DS_CARGO = 'Gestor(a)' THEN 'Não se aplica'
        WHEN DS_CARGO = 'Gerente' THEN GERENTE.NM_FUNCIONARIO 
        ELSE GESTOR.NM_FUNCIONARIO  
    END AS NM_GESTOR

FROM 
    STG_DB_FUNCIONARIO
    JOIN STG_DB_CARGO ON STG_DB_FUNCIONARIO.CD_CARGO = STG_DB_CARGO.CD_CARGO
    JOIN STG_DB_DEPTO ON STG_DB_DEPTO.CD_DEPTO = STG_DB_CARGO.CD_DEPTO
    JOIN STG_DB_LOJA  ON STG_DB_LOJA.NR_LOJA = STG_DB_DEPTO.NR_LOJA
    LEFT JOIN STG_DB_FUNCIONARIO GERENTE ON STG_DB_FUNCIONARIO.CD_GERENTE = GERENTE.CD_FUNCIONARIO
    LEFT JOIN STG_DB_FUNCIONARIO GESTOR ON GERENTE.CD_GERENTE = GESTOR.CD_FUNCIONARIO